# 배포 환경에서 사용될 설정 (SPRING_PROFILES_ACTIVE=prod)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/memento?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      uri: mongodb://mongodb:27017/${SPRING_DATA_MONGODB_DATABASE}

server:
  port: 8080

app:
  url:
    success: https://memento.shinhanacademy.co.kr/payments/success
    fail: https://memento.shinhanacademy.co.kr/payments/fail