# 로컬 개발 환경에서 사용될 설정
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/memento?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: memento
    password:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    # SQL 로그
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/memento-chat

server:
  port: 9999

logging:
  level:
    # 스프링의 메시징 관련 로그를 DEBUG 레벨로 출력
    org.springframework.messaging: DEBUG
    # 웹소켓 관련 로그를 DEBUG 레벨로 출력
    org.springframework.web.socket: DEBUG

app:
  url:
    success: http://localhost:3000/payments/success
    fail: http://localhost:9999/payments/fail