server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/memento?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: memento

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework.web : DEBUG

aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET_NAME}
    upload-dir: ${AWS_S3_UPLOAD_DIR}

toss:
  secret-key: ${TOSS_SECRET_KEY}
  api-host: https://api.tosspayments.com

app:
  url:
    success: http://localhost:9999/payments/success
    fail: http://localhost:9999/payments/fail
